### ISSUE TITLE
Error with Pico & ESP-01

### ISSUE THREAD

**Issue by mrayonnaise** [adafruit/Adafruit_CircuitPython_ESP_ATcontrol#52]
When interfacing Raspberry Pico to ESP-01 via UART, received 
```
Traceback (most recent call last):
  File "<stdin>", line 167, in <module>
  File "<stdin>", line 129, in main
  File "<stdin>", line 96, in esp_test
  File "/lib/adafruit_espatcontrol/adafruit_espatcontrol.py", line 357, in is_connected
  File "/lib/adafruit_espatcontrol/adafruit_espatcontrol.py", line 126, in begin
AttributeError: 'ESP_ATcontrol' object has no attribute 'cipmux'
```

If I remove the 2 lines (125 & 126) it seems to resolve the issue as a dirty fix. It appears that this particular implementation of the board refuses to use a CIPMUX of 0 just from probing with manual AT commands.

https://github.com/adafruit/Adafruit_CircuitPython_ESP_ATcontrol/blob/96ae96d6ad39204ca876a9a0cc0a35882dd00fa8/adafruit_espatcontrol/adafruit_espatcontrol.py#L126

**Comment by jerryneedell** [comment]
I'm curious if you are still having this problem -- I have not run into it with an esp-01 on a Pico.
If it is still an issue, can you post the code you are running that generated the error.
